# Site settings
baseurl = "https://determined-mestorf-26b83e.netlify.com"
languageCode = "en-us"
title = "Rope's Hand Wash"
theme = "hugo-agency-theme"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source) or
  # most longer texts.
  #
  # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Your name"
  description = "Your description"
  # email = "your@email.com"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Possibility to disable external/additional fonts
  # Exception: Fontawesome
  disableFonts = false

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Navigation
  [params.navigation]
    brand = "Rope's Hand Wash"
    # Optional logo as brand stored in img/
    #logo = "logo.svg"
    services = "Services"
    portfolio = "Portfolio"
    about = "About"
    #team = "Team"
    contact = "Contact"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    [[menu.postpend]]
      url = "http://gohugo.io"
      name = "External link"
      weight = 10


  # Hero section
  [params.hero]
    # To change the background image of the hero, replace 'header-bg.jpg' in
    # the 'static/img' folder.
    title = "Welcome To Rope's Hand Wash!"
    subtitle = "You dirt it, we squirt it!"
    buttonText = "Schedule an appointment"


  # Services section
  [params.services]
    enable = true
    title = "Services"
    subtitle = ""

    [[params.services.row]]

    [[params.services.row.list]]
      icon = "fa-shopping-cart"
      title = "E-Commerce"
      description = ""
      url = "#"

    [[params.services.row.list]]
      icon = "fa-laptop"
      title = "Responsive Design"
      description = ""
      url = "#"

    [[params.services.row.list]]
      icon = "fa-lock"
      title = "Web"
      description = ""
      url = "#"

  # Portfolio section
  [params.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Portfolio"
    subtitle = ""

    [params.portfolio.modal]
      client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Close project"


    # About section
  [params.about]
    enable = true
    title = "About"
    subtitle = "Lorem ipsum dolor sit amet consectetur."
    endpoint = "Be part<br>of our<br>story!"
    
      

#  # Client section
    [params.clients_list]
      enable = true
      # Possibility to center items
      center = true
      # Optional client title specifying the involvement
      title = "Some of the great brands we use to make your ride look brand new"

      # All the clients' logos are stored under 'static/img/logos'.
      # Replace them with your clients's logos.
      # Suggestion: .svg in the size of 280px*80px looks good
      [[params.clients]]
        logo = "3M.jpg"
        link = "#"

      [[params.clients]]
        logo = "rainx.jpg"
        link = "#"

      [[params.clients]]
        logo = "sonax.png"
        link = "#"

      [[params.clients]]
        logo = "torq.jpg"
        link = "#"
        
      [[params.clients]]
        logo = "m.jpg"
        link = "#"

      [[params.clients]]
        logo = "chemicalguys.jpg"
        link = "#"

      [[params.clients]]
        logo = "ryobi.png"
        link = "#"

      [[params.clients]]
        logo = "rigid.jpg"
        link = "#"
        
      

  # Contact section
  [params.contact]
   enable = true
  #  title = "Contact us"
   # subtitle  = "Lorem ipsum dolor sit amet consectetur."
   # buttonText = "Send message"
    # netlify = true

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.
    # postURL = "https://example.com/mailout/"

  #  email = "your@email.com"

    # Success and error message overwrite for async contact form
    #thanks = "Thank you for awesomely contacting us."
    #error = "Message could not be send. Please contact us at mail@example.com instead."

  #  [params.contact.captcha]
      # sitekey = ""

    # 'warning' defines error messages for invalid inputs
   # [params.contact.form.name]
   #   text = "Your Name *"
   #   warning = "Please enter your name."

  #  [params.contact.form.email]
   #   text = "Your Email *"
   #   warning = "Please enter your email address."

    #[params.contact.form.phone]
    #  text = "Your Phone *"
    #  warning = "Please enter your phone number."

   # [params.contact.form.message]
    #  text = "Your Message *"
     # warning = "Please enter a message."

      # Add optional form fields to identify contact forms
      #[[params.contact.form.hidden]]
      #  name = "someID"
      #  value = "example.com"
      #
      #[[params.contact.form.hidden]]
      # Special values for name such as "page" and "site" will be autofilled
      #  name = "page"

  # Footer section
  [params.footer]
    enable = true
    copyright = "©Rope's Hand Wash 2019 Powered by the Agency theme for Hugo"

    [[params.footer.social]]
      icon = "fa-instagram"
      link = "https://www.instagram.com/ropeshandwash/?hl=en"
      title = "Instagram"

    [[params.footer.social]]
      icon = "fa-facebook"
      link = "#"
      title = "Facebook"

    [[params.footer.social]]
      icon = "fa-linkedin"
      link = "#"
      title = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Privacy Policy"
      link = "#"

    [[params.footer.quicklinks]]
      text = "Terms of Use"
      link = "#"
